[package]
name = "u8arc"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Implementation of Nintendo's U8 archive format, found in Skyward Sword for example"

[dependencies]
binrw = "0.14.1"
thiserror = "2.0.9"
