[package]
name = "u8arc"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Implementation of Nintendo's U8 archive format, found in Skyward Sword for example"
repository = "https://github.com/lepelog/u8arc"

[dependencies]
binrw = "0.15.0"
thiserror = "2.0.9"
